
# Configuration à ajouter à pubspec.yaml pour générer automatiquement les icônes

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/edulift-logo-1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/edulift-logo-1024.png"
    background_color: "#ffffff"
    theme_color: "#2563eb"
  windows:
    generate: true
    image_path: "assets/icons/edulift-logo-1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/edulift-logo-1024.png"
  linux:
    generate: true
    image_path: "assets/icons/edulift-logo-1024.png"
